# Site settings
title: george的博客
email: 1063658094@qq.com
description: > # this means to ignore newlines until "baseurl:"
  george的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://geogie.github.io/ # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: 侠客

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
twitter: masonsuyan
weibo: suyan0830
github: suyan
instagram: suyan0830
linkedin: suyan0830

# avatar and Favicon
avatar: http://image.firstleap.cn/image/20170327/1490609628393.jpg
favicon: http://image.firstleap.cn/image/20170327/1490609628393.jpg

# disqus config
disqus:
  shortname: suyan-zh

# google analytics config
ga:
  id: UA-54767140-1
  url: yansu.org

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

